version: '3.7'

services:
  influxdb:
    image: influxdb:latest
    container_name: influxdb
    ports:
      - "8086:8086"
    volumes:
      - influxdb-data:/var/lib/influxdb
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=admin
      - DOCKER_INFLUXDB_INIT_PASSWORD=adminadmin
      - DOCKER_INFLUXDB_INIT_ORG=HSAA
      - DOCKER_INFLUXDB_INIT_BUCKET=5s-cd-teamb
      - DOCKER_INFLUXDB_INIT_RETENTION=4w
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=mySuperSecretToken123!
    restart: always

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana-data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=adminadmin
      # - GF_USERS_ALLOW_SIGN_UP=false
      # - GF_AUTH_ANONYMOUS_ENABLED=false
    depends_on:
      - influxdb
    restart: always

  qdrant:
    image: qdrant/qdrant:latest
    container_name: qdrant
    ports:
      - "6333:6333"    # REST API
      - "6334:6334"    # gRPC
    volumes:
      - qdrant-data:/qdrant/storage
    restart: always
  
  # backend:
  #   build: ./backend
  #   ports:
  #     - "5000:5000"
  #   depends_on:
  #     - influxdb
  #     - qdrant

  # frontend:
  #   build: ./frontend
  #   ports:
  #     - "4000:4000"
  #   depends_on:
  #     - backend

volumes:
  influxdb-data:
  grafana-data:
  qdrant-data:
